### ISSUE TITLE
Tapir -Excel Problem

### ISSUE THREAD

**Issue by Fadel-Fadel** [tapir-test/tapir-extensions#17]
Hi 
 it is the same, if the field in Excel is  number or as text, when i want to bring the value from Excel,
tapir adds also a point after the number
note: this problem is just with the numbers.
Example:  if there ist in the Excel-field a number like 236 then tapir writes it in the website like 236. or sometimes 236.0

**Comment by nils-christian** [comment]
Hi Fadel,

Could you please edit your post and translate it into English? We usually use English for our tickets so that also non-German speaking participants can read them.

Now about your issue: I am not sure that I understand it correctly, but it seems to have something to do with the conversion of values in the Excel module. Keep in mind that we use Spring's conversion service for this.

What exactly is written in the Excel file? 123? Is it written as number or as text (a leading apostrophe can force the value written as text)? And what is the datatype of the value in your test code?

**Comment by Fadel-Fadel** [comment]
![Unbenannt](https://user-images.githubusercontent.com/49525262/56025549-9f9a6100-5d12-11e9-94bf-1978fd7a131e.PNG)

**Comment by Fadel-Fadel** [comment]
![Unbenannt](https://user-images.githubusercontent.com/49525262/56026296-20a62800-5d14-11e9-91f1-5618eee9fb93.PNG)

**Comment by nils-christian** [comment]
I discussed the issue with Fadel and it turned out that the Excel field contained a number, but the datatype was String. The value was therefore (correctly) interpreted as a number (236.0). After adding a leading apostrophe in the Excel file, the value was correctly transfered as 236 into the data structure.

I therefore close this issue.
